// Test Suite: Function and Class Templates Basics
// Estimated Time: 3 hours
// Difficulty: Easy to Moderate

#include "instrumentation.h"

#include <gtest/gtest.h>
#include <string>
#include <type_traits>
#include <vector>

class FunctionClassTemplatesTest : public ::testing::Test
{
protected:
    void SetUp() override
    {
        EventLog::instance().clear();
    }
};

// ============================================================================
// TEST 1: Basic Function Templates - Easy
// ============================================================================

template <typename T> T max_value(T a, T b)
{
    EventLog::instance().record("max_value called");
    return (a > b) ? a : b;
}

TEST_F(FunctionClassTemplatesTest, BasicFunctionTemplates)
{
    int max_int = max_value(10, 20);
    double max_double = max_value(3.14, 2.71);
    std::string max_str = max_value(std::string("apple"), std::string("banana"));

    EXPECT_EQ(max_int, 20);
    EXPECT_EQ(max_double, 3.14);
    EXPECT_EQ(max_str, "banana");

    // Q: How many instantiations of max_value are generated by the compiler?
    // A:
    // R:

    // Q: What happens if you call max_value(10, 3.14)? Does it compile?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("max_value called"), 3);
}

// ============================================================================
// TEST 2: Template Type Deduction - Moderate
// ============================================================================

template <typename T> void process_value(T value)
{
    if constexpr (std::is_pointer_v<T>)
    {
        EventLog::instance().record("process_value: pointer");
    }
    else if constexpr (std::is_reference_v<T>)
    {
        EventLog::instance().record("process_value: reference");
    }
    else
    {
        EventLog::instance().record("process_value: value");
    }
}

TEST_F(FunctionClassTemplatesTest, TemplateTypeDeduction)
{
    int x = 42;
    int* ptr = &x;

    process_value(x);
    process_value(ptr);
    process_value(&x);

    // Q: When calling process_value(x), what type is T deduced as?
    // A:
    // R:

    // Q: When calling process_value(ptr), is T deduced as int or int*?
    // A:
    // R:

    // Q: Template type deduction strips references and cv-qualifiers. What happens
    // Q: when you pass const int&?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("process_value: value"), 1);
    EXPECT_EQ(EventLog::instance().count_events("process_value: pointer"), 2);
}

// ============================================================================
// TEST 3: Basic Class Templates - Easy
// ============================================================================

template <typename T> class Box
{
public:
    explicit Box(T value) : value_(value)
    {
        EventLog::instance().record("Box::ctor");
    }

    T get() const
    {
        return value_;
    }

    void set(T value)
    {
        value_ = value;
        EventLog::instance().record("Box::set");
    }

private:
    T value_;
};

TEST_F(FunctionClassTemplatesTest, BasicClassTemplates)
{
    Box<int> int_box(42);
    Box<std::string> str_box("hello");

    EXPECT_EQ(int_box.get(), 42);
    EXPECT_EQ(str_box.get(), "hello");

    int_box.set(100);
    EXPECT_EQ(int_box.get(), 100);

    // Q: How many Box classes are generated by the compiler?
    // A:
    // R:

    // Q: Box<int> and Box<string> are different types. Can you assign one to the other?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("Box::ctor"), 2);
    EXPECT_EQ(EventLog::instance().count_events("Box::set"), 1);
}

// ============================================================================
// TEST 4: Template with Multiple Type Parameters - Moderate
// ============================================================================

template <typename K, typename V> class Pair
{
public:
    Pair(K key, V value) : key_(key), value_(value)
    {
        EventLog::instance().record("Pair::ctor");
    }

    K key() const
    {
        return key_;
    }
    V value() const
    {
        return value_;
    }

private:
    K key_;
    V value_;
};

TEST_F(FunctionClassTemplatesTest, MultipleTypeParameters)
{
    Pair<int, std::string> p1(1, "one");
    Pair<std::string, double> p2("pi", 3.14);

    EXPECT_EQ(p1.key(), 1);
    EXPECT_EQ(p1.value(), "one");
    EXPECT_EQ(p2.key(), "pi");
    EXPECT_DOUBLE_EQ(p2.value(), 3.14);

    // Q: Pair<int, string> and Pair<string, int> are different types. What does this
    // Q: mean for type safety?
    // A:
    // R:

    // Q: How does Pair compare to std::pair? What additional features does std::pair provide?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("Pair::ctor"), 2);
}

// ============================================================================
// TEST 5: Non-Type Template Parameters - Moderate
// ============================================================================

template <typename T, size_t N> class FixedArray
{
public:
    FixedArray()
    {
        EventLog::instance().record("FixedArray::ctor size=" + std::to_string(N));
    }

    T& operator[](size_t index)
    {
        return data_[index];
    }
    const T& operator[](size_t index) const
    {
        return data_[index];
    }

    constexpr size_t size() const
    {
        return N;
    }

private:
    T data_[N];
};

TEST_F(FunctionClassTemplatesTest, NonTypeTemplateParameters)
{
    FixedArray<int, 5> arr1;
    FixedArray<int, 10> arr2;

    arr1[0] = 42;
    arr2[0] = 100;

    EXPECT_EQ(arr1.size(), 5);
    EXPECT_EQ(arr2.size(), 10);

    // Q: FixedArray<int, 5> and FixedArray<int, 10> are different types. What does this
    // Q: mean for type safety and compile-time checking?
    // A:
    // R:

    // Q: The array size N is a compile-time constant. What optimizations does this enable?
    // A:
    // R:

    // Q: How does FixedArray compare to std::array?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("FixedArray::ctor"), 2);
}

// ============================================================================
// TEST 6: TODO - Implement Template with Default Parameters - Easy
// ============================================================================

// TODO: Implement a Container template with:
// TODO: 1. Type parameter T
// TODO: 2. Non-type parameter Size with default value 10
// TODO: 3. Allocator parameter with default std::allocator<T>

TEST_F(FunctionClassTemplatesTest, DISABLED_TemplateDefaultParameters)
{
    // TODO: Implement Container with default parameters
    // TODO: Test with default size
    // TODO: Test with custom size

    // Q: Default template parameters reduce verbosity. When are they useful?
    // A:
    // R:
}

// ============================================================================
// TEST 7: Template Argument Deduction (CTAD C++17) - Moderate
// ============================================================================

template <typename T> class Wrapper
{
public:
    explicit Wrapper(T value) : value_(value)
    {
        EventLog::instance().record("Wrapper::ctor");
    }

    T get() const
    {
        return value_;
    }

private:
    T value_;
};

TEST_F(FunctionClassTemplatesTest, TemplateArgumentDeduction)
{
    Wrapper w1(42);
    Wrapper w2(std::string("hello"));

    EXPECT_EQ(w1.get(), 42);
    EXPECT_EQ(w2.get(), "hello");

    // Q: C++17 Class Template Argument Deduction (CTAD) allows Wrapper w1(42) without
    // Q: specifying <int>. How does the compiler deduce T?
    // A:
    // R:

    // Q: What happens if the constructor is ambiguous? (e.g., Wrapper(int, double))
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("Wrapper::ctor"), 2);
}

// ============================================================================
// TEST 8: Template Member Functions - Moderate
// ============================================================================

class Container
{
public:
    Container()
    {
        EventLog::instance().record("Container::ctor");
    }

    template <typename T> void add(T value)
    {
        EventLog::instance().record("Container::add<" + std::string(typeid(T).name()) + ">");
    }

    template <typename T> T get() const
    {
        EventLog::instance().record("Container::get<" + std::string(typeid(T).name()) + ">");
        return T{};
    }
};

TEST_F(FunctionClassTemplatesTest, TemplateMemberFunctions)
{
    Container c;

    c.add(42);
    c.add(std::string("hello"));
    c.add(3.14);

    int val = c.get<int>();
    (void)val;

    // Q: Container is not a template, but add and get are template member functions.
    // Q: How many instantiations of add are generated?
    // A:
    // R:

    // Q: Can you mix template and non-template member functions in the same class?
    // A:
    // R:

    EXPECT_EQ(EventLog::instance().count_events("Container::ctor"), 1);
    EXPECT_EQ(EventLog::instance().count_events("Container::add"), 3);
    EXPECT_EQ(EventLog::instance().count_events("Container::get"), 1);
}
